spring:
  application:
    name: spring-ai-functions

  # enable colorized log output
  output:
    ansi:
      enabled: ALWAYS

  #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.1-2025-11-13
sfg:
  aiapp:
    apiNinjasKey: ${API_NINJAS_KEY}