spring:
  application:
    name: spring-ai-functions

  # enable colorized log output
  output:
    ansi:
      enabled: ALWAYS

  #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5
sfg:
  aiapp:
    apiNinjasKey: ${API_NINJAS_KEY}

# logs the advisor on the server console
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG